---
# Source: cassandra/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cassandra
  namespace: cassandra
  labels:
    app.kubernetes.io/name: cassandra
    helm.sh/chart: cassandra-9.1.16
    app.kubernetes.io/instance: cassandra
    app.kubernetes.io/managed-by: Helm
  annotations:
automountServiceAccountToken: true
