---
# Source: cassandra/templates/cassandra-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: cassandra
  namespace: cassandra
  labels:
    app.kubernetes.io/name: cassandra
    helm.sh/chart: cassandra-9.1.16
    app.kubernetes.io/instance: cassandra
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  cassandra-password: "NndVZG9NQ2Y4WQ==" # 6wUdoMCf8Y
